name: Build and Test

on: 
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    types: [ opened, synchronize, closed ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: |
          ls
          dotnet restore
          dotnet tool restore

      - name: Build
        run: |
          dotnet build --configuration Release

      - name: Test
        run: |
          dotnet test
